@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
  TextColor #757575
}

skinparam note {
  BackgroundColor #f5f5f5
  TextColor #757575
}

title Caso de Uso - Creación de Perfil de Docente

[*] --> inicio
note on link
  Administrador del sistema inicia:
  - Proceso de creación de perfil de docente
end note

state inicio {
  [*] --> ingresar_datos
  state "Ingresar datos personales del docente" as ingresar_datos

  ingresar_datos --> verificar_informacion
  note right of ingresar_datos
    Incluye:
    - Nombre
    - Apellido
  end note

  state "Verificar la precisión de la información" as verificar_informacion

  verificar_informacion --> confirmar_creacion
  note right of verificar_informacion
    Verificar la precisión de la información
  end note

  state "Confirmar creación" as confirmar_creacion
  confirmar_creacion --> [*]
  note right of confirmar_creacion
    Perfil de docente creado exitosamente
  end note
}

@enduml


