@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

title Caso de Uso Administración de Horarios - Sistema TimeGuardian

[*] --> iniciar_sesion
note on link
  Administrador de horarios:
  - Inicia sesión en el sistema
end note

state iniciar_sesion {
  [*] --> mostrar_interfaz_principal
  state "Mostrar la interfaz principal" as mostrar_interfaz_principal

  mostrar_interfaz_principal --> seleccionar_visualización_asignaturas
  note right of mostrar_interfaz_principal
    Administrador selecciona:
    - Visualizar asignaturas ofrecidas para una carrera
  end note

  state "Seleccionar visualización de asignaturas" as seleccionar_visualización_asignaturas

  seleccionar_visualización_asignaturas --> mostrar_asignaturas_ofrecidas
  state "Mostrar asignaturas ofrecidas" as mostrar_asignaturas_ofrecidas
  note right of mostrar_asignaturas_ofrecidas
    Muestra asignaturas para la carrera seleccionada
  end note

  mostrar_asignaturas_ofrecidas --> arrastrar_soltar_asignaturas
  state "Arrastrar y soltar asignaturas" as arrastrar_soltar_asignaturas
  note right of arrastrar_soltar_asignaturas
    Administrador realiza:
    - Arrastra y suelta asignaturas en el calendario
  end note

  arrastrar_soltar_asignaturas --> guardar_cambios
  state "Guardar cambios" as guardar_cambios
  note right of guardar_cambios
    - Guarda cambios y actualiza horario académico
    Horario académico actualizado
  end note

  guardar_cambios --> [*]
}

@enduml
