@startuml

skinparam state {
  BackgroundColor #faf4b4
  BorderColor #c90000
}

skinparam note {
  BackgroundColor #f5f5f5
}

skinparam linetype polyline

title Caso de Uso Creación de Horario de Clases - TimeGuardian

INICIO -[#c90000]-> crear_horario
note on link
  **Profesor solicita:**
  - Crear nuevo horario de clases
end note

state crear_horario {
  state "Seleccionar materias" as A
  state "Definir horarios" as B
  state "Confirmar horario" as C

  [*] -[#c90000]-> A
  A -[#c90000]-> B
  note on link
      **Profesor debe elegir:**
      - Materias a impartir
      - Número de horas por materia
  end note
  B -[#c90000]-> C
  note on link
    **Profesor asigna:**
    - Horarios para cada materia
    - Aulas disponibles
  end note
  C -[#green]-> [*]
  note on link
    [conflicto de horarios o aulas]
  end note
}

crear_horario -[#c90000]-> :mostrarHorarioFinal

:mostrarHorarioFinal -[#c90000]-> HORARIO_FINAL

@enduml
